#! /bin/bash

declare -a DOCKER_IDS=()

usage() {
    echo "-t --tag : Image's tag to remove."
}

while [ "$1" != "" ];
do
    case $1 in
        -t | --tag )    shift
                        TAG=$1
                        ;;
        -h | --help )   usage
                        exit 0
                        ;;
    esac
    shift
done

# If a tag is passed, delete all images with that tag.
# otherwise, remove all tags that are not latest
if [ ! -z "$TAG" ]; then
    DOCKER_IDS=$(docker images -a | grep -v TAG | grep $TAG | awk '{print $3}')
else
    DOCKER_IDS=$(docker images -a | grep -v TAG | grep -v latest | awk '{print $3}')
fi

for DOCKER_ID in ${DOCKER_IDS[@]};
do
    docker rmi $DOCKER_ID
done
