#! /bin/bash

USERNAME=$1
EMAIL=$2

ALIASES_FILE="$HOME/.bash_aliases" # Store aliases and useful functions
line_break() {
    FILE_NAME=$1
    echo "" >> $FILE_NAME
}

create_function() {
    FUNCTION_NAME=$1
    ADDITIONAL_EXEC=$2

    echo "${FUNCTION_NAME} () {" >> $ALIASES_FILE
    echo "    echo \"TODO\"" >> $ALIASES_FILE

    if [ ! -z "$ADDITIONAL_EXEC" ]; then
        echo "    ${ADDITIONAL_EXEC}" >> $ALIASES_FILE
    fi

    echo "}" >> $ALIASES_FILE
    line_break
}

add_alias() {
    ALIAS_NAME=$1
    ALIAS_FUNCTION=$2

    echo "alias ${ALIAS_NAME}=\"${ALIAS_FUNCTION}\"" >> $ALIASES_FILE
}

create_file_if_none_exist() {
    FILE_NAME=$1
    if [ ! -f $FILE_NAME ]; then
        touch $FILE_NAME
        echo "Creating ${FILE_NAME}"
    fi
}

create_file_if_none_exist $ALIASES_FILE

add_alias "ls" "ls -l"
line_break $ALIASES_FILE

add_alias "gita"    "git add"
add_alias "gitaa"   "git add --all"
add_alias "gitc"    "git commit -m "
add_alias "gitpl"   "git pull --prune"
add_alias "gitps"   "git push"
add_alias "gits"    "git status"
add_alias "gitl"    "git log --oneline"
line_break $ALIASES_FILE

add_alias "python"  "python3"

create_function "morning"
create_function "night" "shutdown now"

source $ALIASES_FILE

# ------------------------------

git config --global user.name $USERNAME
git config --global user.email $EMAIL

git config --global core.editor "vim"
git config --global color.ui auto
