#! /bin/bash

USERNAME=$1
EMAIL=$2

line_break() {
    echo "" >> $ALIASES_FILE
}

create_function() {
    FUNCTION_NAME=$1
    ADDITIONAL_EXEC=$2

    echo "${FUNCTION_NAME} () {" >> $ALIASES_FILE
    echo "    echo \"TODO\"" >> $ALIASES_FILE

    if [ ! -z "$ADDITIONAL_EXEC" ]; then
        echo "    ${ADDITIONAL_EXEC}" >> $ALIASES_FILE
    fi

    echo "}" >> $ALIASES_FILE
    line_break
}

ALIASES_FILE=".bash_aliases"
cd ~

if [ ! -f $ALIASES_FILE ]; then
    touch $ALIASES_FILE
    echo "Creating ${ALIASES_FILE} file"
fi

echo "alias ls=\"ls -l\"" >> $ALIASES_FILE
line_break

echo "alias gita=\"git add\"" >> $ALIASES_FILE
echo "alias gitaa=\"git add --all" >> $ALIASES_FILE
echo "alias gitc=\"git commit -m \"" >> $ALIASES_FILE
echo "alias gitpl=\"git pull --prune\"" >> $ALIASES_FILE
echo "alias gitps=\"git push\"" >> $ALIASES_FILE
echo "alias gits=\"git status\"" >> $ALIASES_FILE
echo "alias gitl=\"git log --oneline\"" >> $ALIASES_FILE
line_break

create_function "morning"
create_function "night" "shutdown now"

source $ALIASES_FILE

# ------------------------------

git config --global user.name $USERNAME
git config --global user.email $EMAIL

git config --global core.editor "vim"
git config --global color.ui auto
