#! /bin/bash

SEARCH_PATH="."
STAY_ON_DEFAULT=0
VERBOSE=0

usage() {
    echo "-p --path : Add root path to search for git repos and pull from."
    echo "-m --master : Checkout branch, or default branch and pull."
    echo "-v --verbose : Output commands and what the script is doing."
}

print() {
    if [ "$VERBOSE" = 1 ]; then
        echo "$1"
    fi
}

print-output() {
    if [ "$VERBOSE" = 1 ]; then
        echo $($1)
    else
        $($1) >/dev/null 2>&1
    fi
}

find_directories_with_git_repos() {
    REL_PATH="$(find . -type d | grep .git$)"

    for single_path in ${REL_PATH[@]};
    do
        WITHOUT_GIT="${single_path::-5}"
        ABS_PATH="$(pwd)/${WITHOUT_GIT:2}"
        GIT_DIRS+=($ABS_PATH)
    done
}

save_branch_go_to_master () {
    BRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
    HUMAN_READABLE_DIR="$(pwd | rev | cut -d'/' -f1 | rev)"
    DEFAULT_BRANCH="(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"

    print "$HUMAN_READABLE_DIR: $BRANCH"
    if [ "$BRANCH" != "$DEFAULT_BRANCH" ]; then
        NON_MASTER_GIT_BRANCH=$BRANCH
        print-output "git stash push"
        print-output "git checkout $DEFAULT_BRANCH"
    fi
}

switch_back_branch () {
    if [ "$NON_MASTER_GIT_BRANCH" != "" ] && [ "$STAY_ON_DEFAULT" = 0 ]; then
        print-output "git checkout $NON_MASTER_GIT_BRANCH"
        print-output "git stash pop"
    fi
}

declare -a GIT_DIRS=()

while [ "$1" != "" ];
do
    case $1 in
        -p | --path )       shift
                            SEARCH_PATH=$1
                            ;;
        -m | --master )     STAY_ON_DEFAULT=1
                            ;;
        -v | --verbose )    VERBOSE=1
                            ;;
        -h | --help )       usage
                            exit 0
                            ;;
    esac
    shift
done

cd $SEARCH_PATH
find_directories_with_git_repos
for CWD in ${GIT_DIRS[@]};
do
    cd $CWD
    NON_MASTER_GIT_BRANCH=""

    save_branch_go_to_master
    print-output "git pull --prune"
    switch_back_branch
    echo
done
echo "Done"
